### ISSUE TITLE
There appears to be duplicate code in the configuration file /etc/systemd/network/lo.network

### ISSUE THREAD

**Issue by CallMeR** [jimdigriz/debian-clearfog-gt-8k#6]
Looking at the configuration file `/etc/systemd/network/lo.network` I found what appears to be duplicate code

```network
[Route]
Destination=64:ff9b::/96
Type=unreachable
[Route]
Destination=64:ff9b::/96
Type=unreachable
```

**Comment by jimdigriz** [comment]
oops, nice catch, something I deployed into 'production' too :)

Fixed, thanks!
